import type { Medicine, PurchaseItem } from '../types';

function daysFromNow(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() + n);
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

export function getSampleData(): Medicine[] {
  const now = new Date().toISOString();
  return [
    {
      id: 'sample-1',
      name: '布洛芬缓释胶囊',
      category: '解热镇痛',
      specification: '0.3g*20粒',
      remainingQuantity: 15,
      minimumQuantity: 10,
      expireDate: daysFromNow(120),
      storageLocation: '客厅药箱',
      usageNotes: '用于缓解轻至中度疼痛，发热时服用。每次1粒，每日2次。',
      status: 'normal',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'sample-2',
      name: '感冒灵颗粒',
      category: '感冒用药',
      specification: '10g*9袋',
      remainingQuantity: 2,
      minimumQuantity: 5,
      expireDate: daysFromNow(20),
      storageLocation: '客厅药箱',
      usageNotes: '感冒引起的头痛、发热、鼻塞、流涕。开水冲服，一次1袋，一日3次。',
      status: 'attention',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'sample-3',
      name: '健胃消食片',
      category: '消化用药',
      specification: '0.5g*64片',
      remainingQuantity: 0,
      minimumQuantity: 20,
      expireDate: daysFromNow(300),
      storageLocation: '厨房抽屉',
      usageNotes: '',
      status: 'to_purchase',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'sample-4',
      name: '碘伏消毒液',
      category: '外用消毒',
      specification: '100ml',
      remainingQuantity: 1,
      minimumQuantity: 2,
      expireDate: daysFromNow(-15),
      storageLocation: '急救包',
      usageNotes: '皮肤消毒用。外用，用棉签蘸取少量，由中心向外周局部涂擦。',
      status: 'stopped',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'sample-5',
      name: '氯雷他定片',
      category: '抗过敏',
      specification: '10mg*6片',
      remainingQuantity: 4,
      minimumQuantity: 3,
      expireDate: daysFromNow(180),
      storageLocation: '卧室床头柜',
      usageNotes: '缓解过敏性鼻炎、荨麻疹等过敏症状。每日1片。',
      status: 'purchased',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'sample-6',
      name: '创可贴',
      category: '外用消毒',
      specification: '100片装',
      remainingQuantity: 85,
      minimumQuantity: 30,
      expireDate: daysFromNow(400),
      storageLocation: '急救包',
      usageNotes: '小伤口止血护创。',
      status: 'normal',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'sample-7',
      name: '蒙脱石散',
      category: '消化用药',
      specification: '3g*10袋',
      remainingQuantity: 3,
      minimumQuantity: 5,
      expireDate: '',
      storageLocation: '厨房抽屉',
      usageNotes: '成人及儿童急、慢性腹泻。',
      status: 'to_purchase',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'sample-8',
      name: '维生素C片',
      category: '营养补充',
      specification: '100mg*100片',
      remainingQuantity: 45,
      minimumQuantity: 30,
      expireDate: daysFromNow(50),
      storageLocation: '卧室床头柜',
      usageNotes: '补充维生素C，增强免疫力。每日1片。',
      status: 'normal',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'sample-9',
      name: '板蓝根颗粒',
      category: '感冒用药',
      specification: '10g*20袋',
      remainingQuantity: 18,
      minimumQuantity: 10,
      expireDate: daysFromNow(200),
      storageLocation: '客厅药箱',
      usageNotes: '清热解毒，用于病毒性感冒、咽喉肿痛。',
      status: 'normal',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'sample-10',
      name: '体温计',
      category: '医疗器械',
      specification: '电子体温计',
      remainingQuantity: 1,
      minimumQuantity: 1,
      expireDate: '',
      storageLocation: '客厅药箱',
      usageNotes: '测量体温用。',
      status: 'normal',
      createdAt: now,
      updatedAt: now,
    },
  ];
}

export function getSamplePurchaseItems(): PurchaseItem[] {
  const now = new Date().toISOString();
  return [
    {
      id: 'sample-purchase-1',
      medicineId: 'sample-3',
      quantity: 20,
      priority: 'high',
      notes: '库存为零，急需补购',
      plannedDate: daysFromNow(1),
      completed: false,
      completedAt: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'sample-purchase-2',
      medicineId: 'sample-7',
      quantity: 5,
      priority: 'medium',
      notes: '日常补购',
      plannedDate: daysFromNow(5),
      completed: false,
      completedAt: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'sample-purchase-3',
      medicineId: 'sample-5',
      quantity: 4,
      priority: 'medium',
      notes: '过敏季前补购，已回填库存',
      plannedDate: daysFromNow(-12),
      completed: true,
      completedAt: daysFromNow(-12),
      createdAt: now,
      updatedAt: daysFromNow(-12),
    },
  ];
}
